logger:
  classname: salina.logger.TFLogger
  log_dir: ./td3
  modulo: 10
  every_n_seconds: 10
  verbose: True

n_envs: 1
env_name: walker2d-random-v2

action_agent:
  classname: salina_examples.offline_rl.bc.agents.ActionMLPAgent
  hidden_size: 256
  n_layers: 2
  env:
    classname: salina_examples.offline_rl.bc.agents.make_d4rl_env
    env_name: ${env_name}
    max_episode_steps: 1000

algorithm:
  env:
    classname: salina_examples.offline_rl.bc.agents.make_d4rl_env
    env_name: ${env_name}
    max_episode_steps: 1000

  dataset_proportion: 0.01
  env_seed: 432
  batch_size: 128
  max_epoch: 10000000
  clip_grad: 2
  optimizer:
    classname: torch.optim.Adam
    lr: 0.001

  loss_device: cpu

  buffer_time_size: 2
  buffer_size: 10000000

  evaluation:
    env_seed: 23
    n_envs: 32
    n_processes: 4
    n_timesteps: 1000
