logger:
  classname: salina.logger.TFLogger
  log_dir: ./td3
  modulo: 10
  every_n_seconds: 10
  verbose: True

n_envs: 1
env_name: pong-expert-v0

action_agent:
  classname: salina_examples.offline_rl.bc.agents.AtariAgent
  env:
    classname: salina_examples.offline_rl.bc.agents.make_d4rl_env
    env_name: ${env_name}
    max_episode_steps: 1000

algorithm:
  env:
    classname: salina_examples.offline_rl.bc.agents.make_d4rl_env
    env_name: ${env_name}
    max_episode_steps: 1000

  dataset_proportion: 0.01
  env_seed: 432
  batch_size: 128
  max_epoch: 10000000
  clip_grad: 2
  optimizer:
    classname: torch.optim.Adam
    lr: 0.001

  loss_device: cpu

  buffer_time_size: 2

  evaluation:
    env_seed: 23
    n_envs: 32
    n_processes: 1
    n_timesteps: 100
