logger:
  classname: salina.logger.TFLogger
  log_dir: ./td3
  modulo: 100
  every_n_seconds: 300
  verbose: True

n_envs: 1
env_name: HalfCheetah-v3
n_timesteps: 50

q_agent:
  classname: salina_examples.rl.td3.agents.QMLPAgent
  hidden_size: 256
  n_layers: 2
  env:
    classname: salina_examples.rl.td3.agents.make_gym_env
    env_name: ${env_name}
    max_episode_steps: 1000

action_agent:
  classname: salina_examples.rl.td3.agents.ActionMLPAgent
  hidden_size: 256
  n_layers: 2
  env:
    classname: salina_examples.rl.td3.agents.make_gym_env
    env_name: ${env_name}
    max_episode_steps: 1000

algorithm:
  env:
    classname: salina_examples.rl.td3.agents.make_gym_env
    env_name: ${env_name}
    max_episode_steps: 1000

  env_seed: 432
  batch_size: 128
  max_epoch: 10000000

  optimizer:
    classname: torch.optim.Adam
    lr: 0.0001

  action_noise: 0.1
  burning_timesteps: 0
  clip_grad: 2
  inner_epochs: ${n_timesteps}
  discount_factor: 0.995
  update_target_tau: 0.005
  loss_device: cuda:0

  n_envs: ${n_envs}
  n_processes: ${n_envs}
  n_timesteps: ${n_timesteps}
  overlapping_timesteps: 1
  buffer_time_size: 2
  buffer_size: 100000
  initial_buffer_size: 10000

  evaluation:
    evaluate: True
    env_seed: 23
    n_envs: 16
    n_processes: 4
    n_timesteps: 10000


hydra:
  launcher:
    nodes: 1
    mem_gb: 64
    max_num_timeout: 0
    cpus_per_task: 10
    signal_delay_s: 30
    timeout_min: 780
    gpus_per_node: 1
    tasks_per_node: 1
    partition: learnfair
  job_logging:
    root:
      handlers: []

defaults:
  - hydra/launcher: submitit_slurm
