name: forgetting_long
classname: salina_cl.scenarios.scenario.BraxScenario
domain: halfcheetah
tasks: ["hugefoot","moon","carry_stuff","rainfall"]
repeat_scenario: 2
n_train_envs: 128
n_evaluation_envs: 512
n_steps: 1_000_000