benchmark_id: '1'
name: halfcheetah_benchmark${scenario.benchmark_id}
classname: salina_cl.scenarios.brax.halfcheetah.halfcheetah_benchmark${scenario.benchmark_id}
n_train_envs: 512
n_evaluation_envs: 512
n_steps: 10_000_000