logger:
  classname: salina.logger.TFLogger
  log_dir: ./td3
  modulo: 100
  every_n_seconds: 60
  verbose: True

n_envs: 256
env_name: halfcheetah
n_timesteps: 8

q_agent:
  classname: salina_examples.rl.td3.agents.QMLPAgent
  hidden_size: 256
  n_layers: 2
  env:
    classname: brax.envs.create_gym_env
    env_name: ${env_name}

action_agent:
  classname: salina_examples.rl.td3.agents.ActionMLPAgent
  hidden_size: 256
  n_layers: 2
  env:
    classname: brax.envs.create_gym_env
    env_name: ${env_name}

algorithm:
  brax_env:
    env_name: ${env_name}
    episode_length: 1000

  env_seed: 432
  batch_size: 128
  max_epoch: 10000000

  optimizer:
    classname: torch.optim.Adam
    lr: 0.0001

  target_noise: 0.2
  action_noise: 0.1
  noise_clip: 0.5
  policy_delay: 2
  burning_timesteps: 0
  clip_grad: 2
  inner_epochs: ${n_timesteps}
  discount_factor: 0.99
  update_target_tau: 0.005
  device: cuda:0
  reward_scaling: 1.0

  n_envs: ${n_envs}
  n_processes: 0
  n_timesteps: ${n_timesteps}
  overlapping_timesteps: 1
  buffer_time_size: 2
  buffer_size: 1000000
  initial_buffer_size: 100000

  evaluation:
    evaluate_every: 1000
    n_envs: 256
    n_timesteps: 1010
    env_seed: 46

hydra:
  launcher:
    nodes: 1
    mem_gb: 64
    max_num_timeout: 0
    cpus_per_task: 10
    signal_delay_s: 30
    timeout_min: 120
    gpus_per_node: 1
    tasks_per_node: 1
    partition: learnfair
  job_logging:
    root:
      handlers: []

defaults:
  - hydra/launcher: submitit_slurm
