algorithm:
  learner: 
    classname: algorithms.a2c.A2C
    discount_factor: 0.95
    entropy_coef:  0.001
    critic_coef: 1.0
    a2c_coef: 0.1
    prob_agent:
      classname: models.salina_models.ProbAgent
      hidden_layers: [32]

    action_agent:
      classname: models.salina_models.ActionAgent

    v_agent:
      classname: models.salina_models.V_Agent
      hidden_layers: [32]

    optimizer:
      classname: torch.optim.Adam
      lr: 0.01
    env : ${env}
    device : 'cpu'
      
  env_seed: 432
  n_envs: 4
  num_processes: 2
  n_timesteps: 16
  max_epochs: 10000


env:
  classname: utils.make_gym_env
  env_name: CartPole-v1
  max_episode_steps: 100

logger:
  classname: salina.logger.TFLogger
  log_dir: a2c
  modulo: 1
  verbose: True