logger:
  classname: salina.logger.TFLogger
  log_dir: ./a2c
  every_n_seconds: 10
  modulo: 10
  verbose: True

env_name: Pendulum-v0

action_agent:
  classname: salina_examples.rl.ppo_continuous.agents.PPOMLPActionAgent
  hidden_size: 64
  n_layers: 2
  env:
    classname: salina_examples.rl.ppo_continuous.agents.make_gym_env
    env_name: ${env_name}
    max_episode_steps: 100

critic_agent:
  classname: salina_examples.rl.ppo_continuous.agents.PPOMLPCriticAgent
  hidden_size: 64
  n_layers: 2
  env:
    classname: salina_examples.rl.ppo_continuous.agents.make_gym_env
    env_name: ${env_name}
    max_episode_steps: 100

algorithm:
  env_seed: 432
  n_envs: 32
  n_processes: 4
  clip_grad: 2
  n_timesteps: 10
  overlapping_timesteps: 1
  max_epochs: 10000
  discount_factor: 0.95
  entropy_coef: 0.001
  critic_coef: 3.0
  clip_ratio: 0.2
  pi_epochs: 10
  action_variance: 0.3
  v_epochs: 10
  gae: 0.9

  device: cpu

  env:
    classname: salina_examples.rl.ppo_discrete.agents.make_gym_env
    env_name: ${env_name}
    max_episode_steps: 100

  optimizer:
    classname: torch.optim.Adam
    lr: 0.0001