name: distraction_short
classname: salina_cl.scenarios.scenario.BraxScenario
domain: ant
tasks: ["normal","inverted_actions","normal","inverted_actions"]
repeat_scenario: 1
n_train_envs: 128
n_evaluation_envs: 512
n_steps: 1_000_000