name: transfer_long
classname: salina_cl.scenarios.scenario.BraxScenario
domain: ant
tasks: ["disabled_first_diagonal","disabled_second_diagonal","disabled_forefeet","disabled_backfeet"]
repeat_scenario: 2
n_train_envs: 128
n_evaluation_envs: 512
n_steps: 1_000_000