logger:
  classname: salina.logger.TFLogger
  log_dir: ./td3_mujoco
  modulo: 100
  every_n_seconds: 300
  verbose: True

n_envs: 1

q_agent:
  classname: salina_examples.rl.td3.agents.QMLPAgent
  hidden_size: 256
  n_layers: 2
  env: ${env}

action_agent:
  classname: salina_examples.rl.td3.agents.ActionMLPAgent
  hidden_size: 256
  n_layers: 2
  env: ${env}

algorithm:
  env: ${env}

  env_seed: 432
  batch_size: 128
  max_epoch: 10000000

  optimizer:
    classname: torch.optim.Adam
    lr: 0.0001

  target_noise: 0.2
  action_noise: 0.1
  noise_clip: 0.5
  policy_delay: 2
  burning_timesteps: 0
  clip_grad: 2
  inner_epochs: 10
  discount_factor: 0.995
  update_target_tau: 0.005
  loss_device: cpu

  n_envs: ${n_envs}
  n_processes: ${n_envs}
  n_timesteps: 10
  overlapping_timesteps: 1
  buffer_time_size: 2
  buffer_size: 100000
  initial_buffer_size: 10000


hydra:
  launcher:
    nodes: 1
    mem_gb: 64
    max_num_timeout: 0
    cpus_per_task: ${plus:${algorithm.n_processes},1}
    gpus_per_node: ${n_gpus:${algorithm.loss_device}}
    signal_delay_s: 30
    timeout_min: 780
    tasks_per_node: 1
    partition: learnfair
  job_logging:
    root:
      handlers: []

defaults:
  - hydra/launcher: submitit_slurm
  - env: gym_mujoco
