logger:
  classname: salina.logger.TFLogger
  log_dir: ./ddqn
  modulo: 100
  every_n_seconds: 10
  verbose: False

n_envs: 1
env_name: CartPole-v0

q_agent:
  classname: salina_examples.rl.dqn.agents.DQNMLPAgent
  hidden_size: 32
  env:
    classname: salina_examples.rl.dqn.agents.make_gym_env
    env_name: ${env_name}
    max_episode_steps: 100

algorithm:
  env:
    classname: salina_examples.rl.dqn.agents.make_gym_env
    env_name: ${env_name}
    max_episode_steps: 100

  env_seed: 432
  batch_size: 64
  max_epoch: 100000

  optimizer:
    classname: torch.optim.Adam
    lr: 0.001

  epsilon_start: 1.0
  epsilon_final: 0.01
  epsilon_exploration_decay_per_timestep: 30000
  burning_timesteps: 0
  clip_grad: 2
  discount_factor: 0.99
  hard_target_update: False
  update_target_epochs: 1000
  update_target_tau: 0.005
  loss_device: cpu
  n_envs: ${n_envs}
  n_processes: ${n_envs}
  n_timesteps: 20
  overlapping_timesteps: 1
  buffer_size: 100000
  initial_buffer_size: 10000
  buffer_time_size: 2

  evaluation:
    message: "evaluation is needed if using the evaluation version of DQN"
    env_seed: 23
    n_envs: 4
    n_processes: 4
    n_timesteps: 1000
