logger:
  classname: salina.logger.TFLogger
  log_dir: ./a2c
  every_n_seconds: 10
  modulo: 10
  verbose: True

action_agent:
  classname: salina_examples.rl.ppo_discrete.agents.PPOMLPActionAgent
  hidden_size: 32
  env:
    classname: salina_examples.rl.ppo_discrete.agents.make_gym_env
    env_name: CartPole-v0
    max_episode_steps: 100

critic_agent:
  classname: salina_examples.rl.ppo_discrete.agents.PPOMLPCriticAgent
  hidden_size: 32
  env:
    classname: salina_examples.rl.ppo_discrete.agents.make_gym_env
    env_name: CartPole-v0
    max_episode_steps: 100

algorithm:
  env_seed: 432
  n_envs: 32
  n_processes: 4
  n_timesteps: 5
  overlapping_timesteps: 1
  max_epochs: 10000
  discount_factor: 0.99
  entropy_coef: 0.01
  critic_coef: 1.0
  clip_ratio: 0.2
  pi_epochs: 1
  v_epochs: 1
  gae: 0.7

  device: cpu

  env:
    classname: salina_examples.rl.ppo_discrete.agents.make_gym_env
    env_name: CartPole-v0
    max_episode_steps: 100

  optimizer:
    classname: torch.optim.Adam
    lr: 0.01
