logger:
  classname: salina.logger.TFLogger
  log_dir: ./a2c
  cache_size: 10000
  modulo: 10
  verbose: False

action_agent:
  classname: salina_examples.rl.ppo_discrete.agents.PPOMLPActionAgent
  hidden_size: 32
  env:
    classname: salina_examples.rl.ppo_discrete.agents.make_gym_env
    env_name: CartPole-v0
    max_episode_steps: 100

critic_agent:
  classname: salina_examples.rl.ppo_discrete.agents.PPOMLPCriticAgent
  hidden_size: 32
  env:
    classname: salina_examples.rl.ppo_discrete.agents.make_gym_env
    env_name: CartPole-v0
    max_episode_steps: 100

algorithm:
  env_seed: 432
  n_envs: 8
  n_processes: 4
  n_timesteps: 50
  overlapping_timesteps: 1
  max_epochs: 10000
  discount_factor: 0.95
  entropy_coef: 0.001
  critic_coef: 1.0
  clip_ratio: 0.2
  pi_epochs: 80
  v_epochs: 80
  gae: 0.9

  device: cpu

  env:
    classname: salina_examples.rl.ppo_discrete.agents.make_gym_env
    env_name: CartPole-v0
    max_episode_steps: 100

  optimizer:
    classname: torch.optim.Adam
    lr: 0.01

  evaluation:
    message: "evaluation is needed if using the evaluation version of A2C"
    env_seed: 23
    n_envs: 32
    n_processes: 4
    n_timesteps: 1000
