classname: salina_cl.algorithms.sac.sac
params:
  learning_device: cuda:0
  acquisition_device: cpu
  buffer_device: cuda:0

  optimizer_policy:
    classname: torch.optim.Adam
    lr: 1e-3

  optimizer_q:
    classname: torch.optim.Adam
    lr: 1e-3

  optimizer_entropy:
    classname: torch.optim.Adam
    lr: 1e-3

  control_every_n_epochs: 1000
  n_control_rollouts: 5

  n_processes: 1

  reward_scaling: 1.
  policy_update_delay: 1
  target_update_delay: 1
  time_limit: 0
  
  n_timesteps: 50  ## burning timesteps
  batch_size: 128   ## 128 ,256,512

  init_temperature: 2.7
  target_multiplier: 2.
  
  clip_grad: 0.
  inner_epochs: 50
  grad_updates_per_step: 1.
  discount_factor: 0.99
  update_target_tau: 0.005
  buffer_time_size: 2
  buffer_size: 1_000_000
  initial_buffer_size: 1_000