
run:
  dir: /checkpoint/jbgaya/CRL_subspace/run/${scenario.name}/${name}/${now:%Y-%m-%d_%H-%M-%S}
sweep:
  dir: /checkpoint/jbgaya/CRL_subspace/multirun/${scenario.name}/${name}/${now:%Y-%m-%d_%H-%M-%S}
  subdir: ${hydra.job.num}
job:
  env_set:
    OMP_NUM_THREADS: '1'
    XLA_PYTHON_CLIENT_PREALLOCATE: 'false'
  config:
    override_dirname:
      item_sep: /
      exclude_keys:
        - seed
launcher:
  mem_gb: 16
  max_num_timeout: 0
  cpus_per_task: 1
  signal_delay_s: 30
  timeout_min: 2400
  gpus_per_node: 1
  tasks_per_node: 1
  partition: learnlab
  comment: NIPS2022
job_logging:
  root:
    handlers: []