logger:
  classname: salina.logger.TFLogger
  log_dir: ./ddqn
  modulo: 100
  cache_size: 10000
  verbose: False

n_envs: 1
env_name: PongNoFrameskip-v4

q_agent:
  classname: salina_examples.rl.dqn.agents.DQNAtariAgent
  env:
    classname: salina_examples.rl.dqn.agents.make_atari_env
    env_name: ${env_name}

algorithm:
  env:
    classname: salina_examples.rl.dqn.agents.make_atari_env
    env_name: ${env_name}
    max_episode_steps: 100000

  env_seed: 432
  batch_size: 64
  max_epoch: 100000

  optimizer:
    classname: torch.optim.Adam
    lr: 0.0001

  epsilon: 0.1
  clip_grad: 2
  inner_epochs: 1
  discount_factor: 0.99
  update_target_tau: 0.005
  loss_device: cpu
  n_envs: ${n_envs}
  n_processes: ${n_envs}
  buffer_size: 100000
  initial_buffer_size: 10000

  evaluation:
    message: "evaluation is needed if using the evaluation version of DQN"
    env_seed: 23
    n_envs: 4
    n_processes: 4
    n_timesteps: 1000
