name: ewc
seed: 0

defaults: 
  - logger: logger
  - scenario: halfcheetah/forgetting_short
  - hydra: hydra
  - model/params/algorithm/generic_sac
  - optional model/params/algorithm: ${scenario} # best HPS for sac are loaded if available
  - override hydra/launcher: submitit_slurm

model:
  classname: salina_cl.models.models.TwoSteps
  seed: ${seed}
  params:
    checkpoint: False
    evaluation:
      device: cuda:0
      seed: ${seed}
      n_evaluation_envs: ${scenario.n_evaluation_envs}
      n_rollouts: 10
      evaluate_success: False

    algorithm2:
      classname: salina_cl.algorithms.regularization.ewc
      params:
        device: cuda:0
        n_samples: 2048
        
    policy_agent:
      classname: salina_cl.agents.single_agents.EWCActionAgent
      hidden_size: 256
      input_dimension: nil
      output_dimension: nil
      start_steps: 0
      fisher_coeff: 1. # 0.01,1.,100,10000

    critic_agent:
      classname: salina_cl.agents.single_agents_sac.TwinCritics
      hidden_size: 256
      obs_dimension: nil
      action_dimension: nil