name: ft_n
seed: 0

defaults: 
  - logger: logger
  - scenario: halfcheetah/forgetting_short
  - hydra: hydra
  - model/params/algorithm/generic_sac
  - optional model/params/algorithm: ${scenario} # best HPS for sac are loaded if available
  - override hydra/launcher: submitit_slurm

model:
  classname: salina_cl.models.models.Baseline
  seed: ${seed}
  params:
    checkpoint: False
    evaluation:
      device: cuda:0
      seed: ${seed}
      n_evaluation_envs: ${scenario.n_evaluation_envs}
      n_rollouts: 10
      evaluate_success: False

    policy_agent:
      classname: salina_cl.agents.single_agents.MultiActionAgent
      hidden_size: 256
      input_dimension: nil
      output_dimension: nil
      start_steps: 0

    critic_agent:
      classname: salina_cl.agents.single_agents_sac.TwinCritics
      hidden_size: 256
      obs_dimension: nil
      action_dimension: nil