name: ppo_subspace
seed: 0
save_model: False

defaults: 
  - logger: logger
  - scenario: halfcheetah_hard1
  - algorithm: ppo
  - hydra: hydra
  - override hydra/launcher: submitit_slurm

model:
  classname: salina_cl.models.subspace.TwoSteps
  seed: ${seed}
  params:
    evaluation:
      device: cuda:0
      seed: 10
      n_rollouts: 1
      evaluate_success: False

    algorithm1:
      classname: salina_cl.algorithms.k_shot.k_shot
      params:
        n_processes: 0
        acquisition_device: cuda:0
        k: 512
        n_envs: ${scenario.n_train_envs}
        budget: 0.2
        
    algorithm2: ${algorithm}

    policy_agent:
      classname: salina_cl.agents.subspace_agents.SubspaceActionAgent
      hidden_size: 64
      n_layers: 4
      input_dimension: nil
      output_dimension: nil

      n_initial_anchors: 1
      dist_type: flat

    critic_agent:
      classname: salina_cl.agents.subspace_agents.CriticAgent
      hidden_size: 256
      n_layers: 4
      input_dimension: nil
      n_anchors:
