name: ppo_finetune
seed: 0
save_model: False
perf_path: /checkpoint/jbgaya/CRL_subspace/multirun/${scenario.name}/${name}/${now:%Y-%m-%d_%H-%M-%S}/perf_per_experiment.dat

defaults:
  - logger: logger
  - scenario: halfcheetah_hard1
  - algorithm: ppo
  - hydra: hydra
  - override hydra/launcher: submitit_slurm

model:
  classname: salina_cl.models.models.OneStep
  seed: ${seed}
  params:
    evaluation:
      device: cuda:0
      seed: 10
      n_rollouts: 5
      evaluate_success: False

    algorithm: ${algorithm}

    policy_agent:
      classname: salina_cl.agents.single_agents.ActionAgent
      hidden_size: 64
      n_layers: 4
      input_dimension: nil
      output_dimension: nil

    critic_agent:
      classname: salina_cl.agents.single_agents.CriticAgent
      hidden_size: 256
      n_layers: 4
      input_dimension: nil