name: ppo_custom
seed: 0
save_model: False
perf_path: /checkpoint/jbgaya/CRL_subspace/multirun/${scenario.name}/${name}/${now:%Y-%m-%d_%H-%M-%S}/perf_per_experiment.dat

defaults:
  - logger: logger
  - scenario: halfcheetah_2tasks
  - algorithm: ppo
  - override hydra/launcher: submitit_slurm

model:
  classname: salina_cl.models.models.OneStep
  seed: ${seed}
  params:
    evaluation:
      device: cuda:0
      seed: ${seed}
      n_rollouts: 1
      evaluate_success: False

    algorithm: ${algorithm}
  
    policy_agent:
      classname: salina_cl.agents.single_agents.ActionAgent
      hidden_size: 64
      n_layers: 4
      input_dimension: nil
      output_dimension: nil

    critic_agent:
      classname: salina_cl.agents.single_agents.CriticAgent
      hidden_size: 256
      n_layers: 4
      input_dimension: nil

hydra:
  run:
    dir: /checkpoint/jbgaya/CRL_subspace/run/${scenario.name}/${name}/${now:%Y-%m-%d_%H-%M-%S}/seed=${seed}
  sweep:
    dir: /checkpoint/jbgaya/CRL_subspace/multirun/${scenario.name}/${name}/${now:%Y-%m-%d_%H-%M-%S}/seed=${seed}
    subdir: ${hydra.job.num}
  job:
    env_set:
      OMP_NUM_THREADS: '1'
      XLA_PYTHON_CLIENT_PREALLOCATE: 'false'
    config:
      override_dirname:
        item_sep: /
        exclude_keys:
          - seed
  launcher:
    mem_gb: 16
    max_num_timeout: 0
    cpus_per_task: 1
    signal_delay_s: 30
    timeout_min: 30
    gpus_per_node: 1
    tasks_per_node: 1
    partition: learnlab
    comment: CoLLa2022
  job_logging:
    root:
      handlers: []