name: sac_subspace
seed: 0
perf_path: results/test.dat
save_model: False
final_evaluation: False

defaults:
  - logger: logger
  - scenario: halfcheetah_benchmark
  - hydra: hydra
  - evaluation: evaluation_subspace
  - override hydra/launcher: submitit_slurm

model:
  classname: salina_cl.models.subspace.Subspace
  seed: ${seed}
  params:
    checkpoint: True
    evaluation:
      device: cuda:0
      n_evaluation_envs: ${scenario.n_evaluation_envs}
      seed: 1
      n_rollouts: 5
      scale: 89 #For building the triangle 44 -> 1035 / 63 -> 2080 / 89 -> 4095
      steps: 4095
      evaluate_success: False

    lr_scaling:  0. #scaling of the lr * nb_anchors
    algorithm: 
      classname: salina_cl.algorithms.sac.sac
      params:
        learning_device: cuda:0
        acquisition_device: cuda:0
        buffer_device: cuda:0
    
        optimizer_policy:
          classname: torch.optim.Adam
          lr: 1e-3
    
        optimizer_q:
          classname: torch.optim.Adam
          lr: 1e-3

        optimizer_entropy:
          classname: torch.optim.Adam
          lr: 3e-4
    
        control_every_n_epochs: 100
        n_control_rollouts: 1
      
        n_processes: 0
  
        reward_scaling: 1.
        policy_update_delay: 4
        target_update_delay: 2
        time_limit: 0
        
        n_timesteps: 2
        batch_size: 256

        init_temperature: 2.
        target_multiplier: 2.
       
        clip_grad: 0.
        inner_epochs: ${scenario.n_train_envs}
        grad_updates_per_step: 0.5
        discount_factor: 0.99
        update_target_tau: 0.005
        buffer_time_size: 2
        buffer_size: 1_280_000
        initial_buffer_size: 12_800

    k_shot:
      classname: salina_cl.algorithms.k_shot.k_shot
      params:
        device: cuda:0
        n_envs: ${scenario.n_train_envs}
        n_max_interactions: 128_001
        n_processes: 0
        time_size: ${model.params.algorithm.params.buffer_time_size}

    alpha_search:
      classname: salina_cl.algorithms.alpha_search.value_estimation
      params:
        device: cuda:0
        n_estimations: 1024
        steps: 4096
        scale: 89
        n_processes: 0
        n_rollouts: 5
        improvement_threshold: 0.1
        time_size: ${model.params.algorithm.params.buffer_time_size}

    policy_agent:
      classname: salina_cl.agents.subspace_agents_sac.SubspaceActionAgent
      hidden_size: 256
      input_dimension: nil
      output_dimension: nil
      start_steps: 0

      n_initial_anchors: 1
      dist_type: flat
      refresh_rate: 1.
      resampling_q: False
      resampling_policy: False

    critic_agent:
      classname: salina_cl.agents.subspace_agents_sac.TwinCritics
      hidden_size: 256
      obs_dimension: nil
      action_dimension: nil
      n_anchors:
